### ISSUE TITLE
Simple questions

### ISSUE THREAD

**Issue by mibamur** [sciactive/2be-extras#1]
Hello @sciactive !

Excuse me! Can you allow PR in https://github.com/sciactive/pnotify ?

PS
Sorry that I must write it there
but your site is unavailable and pnotify last commit 4 month ago

**Comment by hperrin** [comment]
Hi Michael. I'm not sure what you mean by PR.

**Comment by mibamur** [comment]
PR - pull request )

**Comment by hperrin** [comment]
Oh. Yes. I'll actually be working on a fork of Pines called WonderPHP which
will have more interaction with the community, and new features for scaling
(database sharding, new database design, JavaScript modules, etc). I'll
hopefully be implementing it at my new job, which is looking for a better,
scalable CMS. So I'll be taking over the jQuery plugins again. (I left
about a year ago to work for Facebook.)

**Comment by hperrin** [comment]
Archiving repo.
